version: "2"

services:
  mysql-local:
    build: docker/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "ethereumoracle"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_HOST: 0.0.0.0
    ports:
      - "3307:3306"
    expose:
      - "3307"
      - "3306"
  oracle:
    build: .
    depends_on:
      - mysql-local
    links:
      - mysql-local
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - MYSQL_HOST=mysql-local
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-local:3306/ethereumoracle?autoReconnect=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    restart: on-failure
