spring:
  profiles: default
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ethereumoracle?autoReconnect=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password:


hibernate.hbm2ddl.auto: create-drop